Added EIP-1967 support
zkBob/stable-nft pull request #51
Opened 2022-12-17 09:38 UTC by AlexSaplin

2022-12-19 10:16 UTC, YusupovAI approved these changes

2022-12-19 14:13 UTC, k1rill-fedoseev requested changes

2022-12-19 14:13 UTC, k1rill-fedoseev commented on src/utils/DefaultAccessControlLateInit.sol
> +contract DefaultAccessControlLateInit is IDefaultAccessControl, AccessControlEnumerable {
Let's rename this to something like `VaultAccessControl`?

2022-12-19 14:13 UTC, k1rill-fedoseev commented on src/utils/DefaultAccessControlLateInit.sol
> +    function init(address admin) public {
I think this function should be internal

2022-12-19 14:13 UTC, k1rill-fedoseev commented on src/utils/DefaultAccessControlLateInit.sol
> +    bool public initialized;
I think it's better to move `initialized` variable and its logic in the `Vault` contract, near to `isPaused`, `isPublic`

2022-12-19 14:13 UTC, k1rill-fedoseev commented on src/Vault.sol
> +        token = IMUSD(token_);
Let's also set `initialized` to `true` here. This will ensure implementation contract can only be used through the proxy contract.

2022-12-21 06:37 UTC, k1rill-fedoseev approved these changes

2022-12-21 06:37 UTC, k1rill-fedoseev commented on src/Vault.sol
> +        VaultAccessControl.init(admin);
Let's prepend all internal functions with an underscore and call them directly, without contract name.
e.g. `_initRoles(admin)` would be fine for me.

2022-12-21 06:59 UTC, merged